const BLOCK_SIZE = 48;

class World {
    constructor(Texturepack) {
        this.debugName = "World";

        this.isLoaded = false;

        this.Texturepack = Texturepack;

        this.Texturepack.load();
        this.textures = Texturepack.textures;

        this.offsetX = 0;
        this.offsetY = 0;

        // FIX THISSS

        setTimeout(() => {
            this.isLoaded = true;
        }, 1000);

        // ---------

        // Old map with Id system, which we kinda hate a lil bit, so it is not in use anymore...
        // this.map = [
        //     // 1  2  3  4  5  6  7  8  9  10
        //     [2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
        //     [2, 2, 2, 2, 0, 2, 2, 2, 2, 2],
        //     [2, 2, 2, 2, 0, 2, 2, 2, 2, 2],
        //     [2, 2, 2, 2, 0, 2, 2, 2, 2, 2],
        //     [2, 2, 2, 2, 0, 2, 2, 2, 2, 2],
        //     [2, 2, 2, 2, 0, 2, 2, 2, 2, 2],
        //     [2, 2, 2, 2, 0, 2, 2, 2, 2, 2],
        //     [2, 2, 2, 2, 0, 2, 2, 2, 2, 2],
        //     [2, 2, 2, 2, 0, 2, 2, 2, 2, 2],
        //     [2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
        // ];

        //The test map with word ids..

        this.map = [
            [
                "Bedrock",
                "Bedrock",
                "Bedrock",
                "Bedrock",
                "Bedrock",
                "Bedrock",
                "Bedrock",
                "Bedrock",
                "Bedrock",
                "Bedrock",
                "Bedrock",
                "Bedrock",
                "Bedrock",
                "Bedrock",
                "Bedrock",
                "Bedrock",
                "Bedrock",
                "Bedrock",
                "Bedrock",
                "Bedrock",
                "Bedrock",
                "Bedrock",
                "Bedrock",
                "Bedrock",
                "Bedrock",
                "Bedrock",
                "Bedrock",
                "Bedrock",
                "Bedrock",
                "Bedrock",
                "Bedrock",
                "Bedrock",
                "Bedrock",
                "Bedrock",
                "Bedrock",
                "Bedrock",
                "Bedrock",
                "Bedrock",
                "Bedrock",
                "Bedrock",
            ],
            [
                "Bedrock",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Bedrock",
            ],
            [
                "Bedrock",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Bedrock",
            ],
            [
                "Bedrock",
                "Grass",
                "",
                "",
                "Dirt",
                "Dirt",
                "Stone",
                "Stone",
                "Sand",
                "Sand",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Bedrock",
            ],
            [
                "Bedrock",
                "Grass",
                "",
                "",
                "Dirt",
                "Dirt",
                "Stone",
                "Stone",
                "Sand",
                "Sand",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Bedrock",
            ],
            [
                "Bedrock",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Bedrock",
            ],
            [
                "Bedrock",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Bedrock",
            ],
            [
                "Bedrock",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Bedrock",
            ],
            [
                "Bedrock",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Bedrock",
            ],
            [
                "Bedrock",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Bedrock",
            ],
            [
                "Bedrock",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Bedrock",
            ],
            [
                "Bedrock",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Bedrock",
            ],
            [
                "Bedrock",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Bedrock",
            ],
            [
                "Bedrock",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Bedrock",
            ],
            [
                "Bedrock",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Bedrock",
            ],
            [
                "Bedrock",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Bedrock",
            ],
            [
                "Bedrock",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Bedrock",
            ],
            [
                "Bedrock",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Bedrock",
            ],
            [
                "Bedrock",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Sand",
                "Sand",
                "Sand",
                "Sand",
                "Sand",
                "Sand",
                "Sand",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Bedrock",
            ],
            [
                "Bedrock",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Sand",
                "Sand",
                "Sand",
                "Sand",
                "Sand",
                "Sand",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Bedrock",
            ],
            [
                "Bedrock",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Sand",
                "Sand",
                "Sand",
                "Sand",
                "Sand",
                "Sand",
                "Sand",
                "Sand",
                "Sand",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Bedrock",
            ],
            [
                "Bedrock",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Grass",
                "Bedrock",
            ],
            [
                "Bedrock",
                "Bedrock",
                "Bedrock",
                "Bedrock",
                "Bedrock",
                "Bedrock",
                "Bedrock",
                "Bedrock",
                "Bedrock",
                "Bedrock",
                "Bedrock",
                "Bedrock",
                "Bedrock",
                "Bedrock",
                "Bedrock",
                "Bedrock",
                "Bedrock",
                "Bedrock",
                "Bedrock",
                "Bedrock",
                "Bedrock",
                "Bedrock",
                "Bedrock",
                "Bedrock",
                "Bedrock",
                "Bedrock",
                "Bedrock",
                "Bedrock",
                "Bedrock",
                "Bedrock",
                "Bedrock",
                "Bedrock",
                "Bedrock",
                "Bedrock",
                "Bedrock",
                "Bedrock",
                "Bedrock",
                "Bedrock",
                "Bedrock",
                "Bedrock",
            ],
        ];

        this.blocks = {};
    }

    Draw() {
        this.renderMap();
    }

    LoadMap(map) {
        //read some json.. But that comes later ;)
    }

    // renderMap() {
    //     background(255);
    //     let tileImg, mapRow;

    //     //DEBUG && console.log(`[${this.debugName}] Starting world render`);

    //     if (this.textures) {
    //         for (var i = 0; i < this.map.length; i++) {
    //             mapRow = this.map[i];
    //             for (var j = 0; j < mapRow.length; j++) {
    //                 let imgName = mapRow[j] + "_texture";

    //                 if (imgName in this.textures) {
    //                     tileImg = this.textures[imgName];
    //                 } else {
    //                     tileImg = this.Texturepack.undefinedTexture;
    //                 }

    //                 noSmooth(); //Removing pixel interpolation
    //                 image(
    //                     tileImg,
    //                     j * BLOCK_SIZE - this.offsetX,
    //                     i * BLOCK_SIZE - this.offsetY,
    //                     BLOCK_SIZE,
    //                     BLOCK_SIZE
    //                 );
    //                 smooth();
    //             }
    //         }
    //     }

    //     //DEBUG && console.log(`[${this.debugName}] World rendered`);

    //     this.isLoaded = true;
    // }

    renderMap() {
        "Stone";
    }

    checkCollisions() {
        let mapRow, blockX, blockY, currentBlock;

        for (var i = 0; i < this.map.length; i++) {
            mapRow = this.map[i];
            for (var j = 0; j < mapRow.length; j++) {
                currentBlock = this.map[i][j];

                blockX = j * BLOCK_SIZE - this.offsetX;
                blockY = i * BLOCK_SIZE - this.offsetY;

                if (
                    player.xx < blockX + BLOCK_SIZE &&
                    player.xx + player.ww > blockX &&
                    player.yy < blockY + BLOCK_SIZE &&
                    player.yy + player.hh > blockY
                ) {
                    if (currentBlock == "Stone" || currentBlock == "Bedrock") {
                        player.state = "IdleState";
                        player.xx = player.xx + 10 * (player.directionX * -1);
                        player.yy = player.yy + 10 * (player.directionY * -1);
                    }
                }
            }
        }
    }

    renderWindow() {
        const PADDING_RANGE = BLOCK_SIZE;
        const OFFSET_UPDATE = 6.4;

        if (player.xx > CANVAS_SIZE_W - PADDING_RANGE - player.ww) {
            this.offsetX += OFFSET_UPDATE;
            player.xx = CANVAS_SIZE_W - PADDING_RANGE - player.ww;
        }
        if (player.xx < PADDING_RANGE) {
            this.offsetX -= OFFSET_UPDATE;
            player.xx = PADDING_RANGE;
        }
        if (player.yy > CANVAS_SIZE_H - PADDING_RANGE - player.hh) {
            this.offsetY += OFFSET_UPDATE;
            player.yy = CANVAS_SIZE_H - PADDING_RANGE - player.hh;
        }
        if (player.yy < PADDING_RANGE) {
            this.offsetY -= OFFSET_UPDATE;
            player.yy = PADDING_RANGE;
        }
        if (this.offsetX < 0) {
            this.offsetX = 0;
        }
        if (this.offsetY < 0) {
            this.offsetY = 0;
        }
    }
}
